# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
School.create(name: 'Dracut High School', district: 'Dracut', school_type: 'High School', students: 859, location: '1540 Lakeview Ave, Dracut MA 01826', dollars_per_student: 10000, number_of_ap_classes: '0', lat: 42.6745179, lng: -71.3364292)
School.create(name: 'Cambridge Ringe-Latin', district: 'Cambridge', school_type: 'High School', students: 1836, location: '459 Broadway, Cambridge MA 02138', dollars_per_student: 27000, number_of_ap_classes: '1', lat: 42.3744083, lng: -71.11061359999997)

Course.create(name: 'Digital Applications', description: ' (.5 credits)This course will teach students skills necessary for the 21st century world. Students will learn Microsoft Office, Google Apps and other web based resources. Students will expand their current technological skills and develop new expertise in digital tools. Topics include creating a digital portfolio, digital citizenship, technology operations, and information fluency. Recommended for all levels. 21st century learner expectation: utilize an array of methods to research, analyze, and problem solve; use technology effectively and responsibly')
Course.create(name: 'Gaming and Music Program', description: '(.5 credits)This course is for students interested in creating online games and/or their own music. Using a free program created by MIT called “Scratch” you will create animation, games, and other programs by “clicking together” programming constructs represented as building blocks. “Scratch” emphasizes the practical learning of fundamental computer science concepts and at the same time supports the idea of fostering creativity in computer science classes. This course is open to all students. 21st century learner expectation: utilize an array of methods to research, analyze, and problem solve use technology effectively and responsibly.')
Course.create(name: 'Introduction to Computer Schience: Exploring Programming', description: 'This course is designed for students who have had no previous programming experience. The software package Alice features a development environment using 3D graphics to introduce students to computer programming and the Java language. Students will use Alice throughout the course to create projects in small virtual worlds using 3D models and Java programs. Students may also be exposed to other programming languages such as Python and Scratch. The course is intended not only to familiarize students with computer programming, but also to sharpen problem-solving skills. Honors designation can be earned by completing additional assignments and projects. This class can be taken for mathematics or RSTA credit. See also page 48. Length: One Semester; Grades: 9-12; Credits: 10; Prerequisite: Passing Grade in Algebra I ')
Course.create(name: 'AP Computer Science', description: 'The AP Computer Science course is an introductory course in computer science. Because the design and implementation of computer programs to solve problems involve skills that are fundamental to the study of computer science, a large part of the course is built around the development of computer programs that correctly solve a given problem. These programs should be understandable, adaptable, and, when appropriate, reusable. At the same time, the design and implementation of computer programs is used as a context for introducing other important aspects of computer science, including the development and analysis of algorithms, the development and use of fundamental data structures, the study of standard algorithms and typical applications, and the use of logic and formal methods. In addition, the responsible use of these systems is an integral part of the course. This course is a joint CRLS and Microsoft Corporation TEALS Program initiative and will be co-taught by a Microsoft employee and a CRLS teacher. Length: One Semester; Grades: 10-12; Credits: 10; Prerequisite: Passing grade in Algebra 2 ')

SchoolCourse.create(school_id: 1, course_id: 1)
SchoolCourse.create(school_id: 1, course_id: 2)
SchoolCourse.create(school_id: 2, course_id: 3)
SchoolCourse.create(school_id: 2, course_id: 4)
